add custom prompt option to text2cypher, tested
neo4j/neo4j-genai-python pull request #84
Opened 2024-07-29 19:44 UTC by a-s-g93

# Description

Add an option to provide a custom prompt to the Text2Cypher Retriever. Doing so will ignore any provided graph schema or examples.

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] Breaking change
- [x] Documentation update
- [ ] Project configuration change

## Complexity

Low

Complexity:

## How Has This Been Tested?
- [x] Unit tests
- [ ] E2E tests
- [ ] Manual tests

# Checklist

The following requirements should have been met (depending on the changes in the branch):

no E2E tests needed, no examples written, no new files created

- [x] Documentation has been updated
- [x] Unit tests have been updated
- [ ] E2E tests have been updated
- [ ] Examples have been updated
- [ ] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed
- [x] CHANGELOG.md updated if appropriate

2024-07-30 15:33 UTC, willtai commented
Hey @a-s-g93, thanks for the contribution! To pass the CLA check you will need to sign our CLA, [please follow the instructions here](https://neo4j.com/developer/cla/).

2024-07-30 15:41 UTC, a-s-g93 commented
> Hey @a-s-g93, thanks for the contribution! To pass the CLA check you will need to sign our CLA, [please follow the instructions here](https://neo4j.com/developer/cla/).

Hey @willtai I sent an email yesterday with all required info before submitting my PR. How long before CLA info is verified?

2024-07-31 16:24 UTC, willtai requested changes
Nice work! I would also add another test that raises `SearchValidationError` when a wrong type is used for the custom prompt.

Something similar to this https://github.com/neo4j/neo4j-genai-python/blob/main/tests/unit/retrievers/test_text2cypher.py#L73

2024-07-31 16:40 UTC, a-s-g93 commented
> Nice work! I would also add another test that raises `SearchValidationError` when a wrong type is used for the custom prompt.
> 
> Something similar to this https://github.com/neo4j/neo4j-genai-python/blob/main/tests/unit/retrievers/test_text2cypher.py#L73

Thanks for the feedback @willtai! Should I test the `RetrieverInitializationError` error instead since this is caught during initialization?

2024-08-01 10:11 UTC, alexthomas93 commented
> > Nice work! I would also add another test that raises `SearchValidationError` when a wrong type is used for the custom prompt.
> > Something similar to this https://github.com/neo4j/neo4j-genai-python/blob/main/tests/unit/retrievers/test_text2cypher.py#L73
> 
> Thanks for the feedback @willtai! Should I test the `RetrieverInitializationError` error instead since this is caught during initialization?

Yes `RetrieverInitializationError` is the one to test for here @a-s-g93

2024-08-02 09:18 UTC, alexthomas93 commented on tests/unit/retrievers/test_text2cypher.py
> +        Text2CypherRetriever(driver=driver, llm=llm, custom_prompt=42)
```suggestion
        Text2CypherRetriever(driver=driver, llm=llm, custom_prompt=42)  # type: ignore
```
You need to include `# type: ignore` comments in order to pass the mypy check

2024-08-02 09:18 UTC, alexthomas93 commented on tests/unit/retrievers/test_text2cypher.py
> +        Text2CypherRetriever(driver=driver, llm=llm, neo4j_schema=42)
```suggestion
        Text2CypherRetriever(driver=driver, llm=llm, neo4j_schema=42)  # type: ignore
```

2024-08-02 09:18 UTC, alexthomas93 commented on tests/unit/retrievers/test_text2cypher.py
> +            examples=42,
```suggestion
            examples=42,  # type: ignore
```

2024-08-02 09:18 UTC, alexthomas93 commented on tests/unit/retrievers/test_text2cypher.py
> +    retriever.driver.execute_query.return_value = (
```suggestion
    retriever.driver.execute_query.return_value = (  # type: ignore
```

2024-08-02 09:18 UTC, alexthomas93 commented on tests/unit/retrievers/test_text2cypher.py
> +    retriever.driver.execute_query.assert_called_once_with(query_=t2c_query)
```suggestion
    retriever.driver.execute_query.assert_called_once_with(query_=t2c_query)  # type: ignore
```

2024-08-06 11:37 UTC, willtai commented
The PR E2E tests have been scaled down to avoid running out of disk space. Please rebase off the latest changes in main to apply these changes to your PR

2024-08-06 15:37 UTC, a-s-g93 commented
I can't pass the mypy pre-commit check due to the `Unused "type: ignore" comment [unused-ignore]` in the test_text2cypher.py file. These comments aren't mine. When I run the mypy check from command line I get a success message. I've tested this with Python 3.10, 3.11 and 3.12. I've tried reinstalling the pre-commit hook and reinstalling the project dependencies. Do you have a recommendation on how to address this?

<img width="967" alt="Screenshot 2024-08-06 at 10 31 40 AM" src="https://github.com/user-attachments/assets/c01b7bcd-4c14-406d-9313-90d0c423ed94">

2024-08-07 15:24 UTC, alexthomas93 approved these changes
LGTM

2024-08-07 17:20 UTC, willtai approved these changes

2024-08-07 17:20 UTC, merged